# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03963b18ce25e8f0922ade0ceb544fd219ea2273ca3353051fe954061880f94d1fff8b25c0c35d06eb174e2c65a607faaec7fab00494764c33e18484392a16bb

test:
  secret_key_base: ba0bb19974a4664795ed29d039c6d6bc61d245bd34f9a7839cf469a0b3ab13436b2766a24d26120f22713de13f98b789a4379edb700c242e40b287025f288b32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
